theme: jekyll-theme-cayman
title: "ReadMETRICS: a Robust Software Bundle for Usage Statistics"
author: GitHub User
email: ezteam at couperin.org
description: "Providing you with a full overview of your institution's electronic resources usage"

# social links
twitter_username: ezpaarse # DO NOT include the @ character, or else the build will fail!
github_username:  ezpaarse-project # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
