theme: jekyll-theme-cayman
title: "ReadMETRICS: a software pack for usage statistics"
author: GitHub User
email: ezteam at couperin.org
description: "ReadMETRICS includes ezPAARSE and ezMESURE and is also able of ingesting COUNTER 5 data, giving you a full overview of electronic resources usage"

# social links
twitter_username: ezpaarse # DO NOT include the @ character, or else the build will fail!
github_username:  ezpaarse-project # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
